"""
MarketIntelligenceService - Infrastructure Layer

SOTA: Strategic Intelligence HQ for live trading.
Provides market conditions analysis to prevent adverse trades.

Key Features:
- Funding Rate Filter: Block trades against crowded direction
- Leverage Cap: Auto-adjust to exchange limits
- Risk Assessment: Evaluate symbol tradability

Data Source: market_intelligence.json (from get_market_intelligence.py)

Reference:
- Institutional funding rate arbitrage strategies (2025-2026)
- Binance perpetual futures mechanics
"""

import logging
import json
import os
from datetime import datetime
from typing import Dict, Optional, Tuple
from dataclasses import dataclass
from decimal import Decimal


@dataclass
class SymbolIntelligence:
    """
    Intelligence data for a single trading symbol.
    """
    symbol: str

    # Trading Rules (also in ExchangeFilterService, but cached here for convenience)
    min_qty: float
    step_size: float
    tick_size: float
    min_notional: float
    qty_precision: int
    price_precision: int

    # Risk Parameters
    max_leverage: int
    max_position_at_max_leverage: float

    # Market Conditions
    funding_rate: float  # Percentage, e.g., -0.065 means -0.065%
    next_funding_time: str
    mark_price: float


class MarketIntelligenceService:
    """
    Strategic Intelligence HQ for live trading.

    Purpose: Evaluate market conditions BEFORE placing orders.
    Works alongside ExchangeFilterService (which handles HOW to order).

    Key Filters:
    1. Funding Rate Filter:
       - Block LONG if funding > +0.05% (crowded longs, squeeze risk)
       - Block SHORT if funding < -0.05% (crowded shorts, squeeze risk)

    2. Leverage Cap:
       - Auto-adjust leverage to exchange maximum if bot wants more

    3. Tradability Check:
       - Check if symbol has valid data

    Usage:
        # At startup
        intel_service = MarketIntelligenceService()
        intel_service.load_from_file()

        # Before placing order
        proceed, reason = intel_service.evaluate_signal("ZECUSDT", "SHORT")
        if not proceed:
            logger.warning(f"Intelligence blocked: {reason}")
            return
    """

    # Funding rate thresholds (institutional standard)
    FUNDING_THRESHOLD_POSITIVE = 0.05  # +0.05%
    FUNDING_THRESHOLD_NEGATIVE = -0.05  # -0.05%
    FUNDING_EXTREME_POSITIVE = 0.10  # +0.10%
    FUNDING_EXTREME_NEGATIVE = -0.10  # -0.10%

    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self._data: Dict[str, SymbolIntelligence] = {}
        self._loaded = False
        self._last_refresh: Optional[datetime] = None
        self._file_path: Optional[str] = None

    def load_from_file(self, file_path: str = None) -> bool:
        """
        Load intelligence data from market_intelligence.json.

        This file is generated by: python backend/scripts/get_market_intelligence.py

        Args:
            file_path: Path to JSON file (default: backend/data/market_intelligence.json)

        Returns:
            True if loaded successfully
        """
        if file_path is None:
            # Default path relative to project root
            base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
            file_path = os.path.join(base_dir, "data", "market_intelligence.json")

        self._file_path = file_path

        try:
            if not os.path.exists(file_path):
                self.logger.warning(f"⚠️ Intelligence file not found: {file_path}")
                return False

            self.logger.info(f"🧠 Loading market intelligence from: {file_path}")

            with open(file_path, 'r') as f:
                raw_data = json.load(f)

            for sym, info in raw_data.items():
                rules = info.get('rules', {})
                risk = info.get('risk', {})
                market = info.get('market', {})

                self._data[sym] = SymbolIntelligence(
                    symbol=sym,
                    min_qty=float(rules.get('min_qty', 0.001)),
                    step_size=float(rules.get('step_size', 0.001)),
                    tick_size=float(rules.get('tick_size', 0.01)),
                    min_notional=float(rules.get('min_notional', 5.0)),
                    qty_precision=int(rules.get('qty_precision', 3)),
                    price_precision=int(rules.get('price_precision', 2)),
                    max_leverage=int(risk.get('max_leverage', 10)) if risk.get('max_leverage') != 'N/A' else 10,
                    max_position_at_max_leverage=float(risk.get('max_position_at_max_leverage', 100000)) if risk.get('max_position_at_max_leverage') != 'N/A' else 100000,
                    funding_rate=float(market.get('funding_rate', 0)),
                    next_funding_time=str(market.get('next_funding_time', 'N/A')),
                    mark_price=float(market.get('mark_price', 0))
                )

            self._loaded = True
            self._last_refresh = datetime.now()

            self.logger.info(f"✅ Loaded intelligence for {len(self._data)} symbols")

            # Log funding warnings
            for sym, intel in self._data.items():
                if intel.funding_rate > self.FUNDING_EXTREME_POSITIVE:
                    self.logger.warning(f"   🔴 {sym}: Funding +{intel.funding_rate:.3f}% (EXTREME CROWDED LONGS)")
                elif intel.funding_rate < self.FUNDING_EXTREME_NEGATIVE:
                    self.logger.warning(f"   🔴 {sym}: Funding {intel.funding_rate:.3f}% (EXTREME CROWDED SHORTS)")
                elif intel.funding_rate > self.FUNDING_THRESHOLD_POSITIVE:
                    self.logger.info(f"   🟡 {sym}: Funding +{intel.funding_rate:.3f}% (crowded longs)")
                elif intel.funding_rate < self.FUNDING_THRESHOLD_NEGATIVE:
                    self.logger.info(f"   🟡 {sym}: Funding {intel.funding_rate:.3f}% (crowded shorts)")

            return True

        except Exception as e:
            self.logger.error(f"❌ Failed to load intelligence: {e}")
            return False

    def get_intelligence(self, symbol: str) -> Optional[SymbolIntelligence]:
        """Get intelligence data for a symbol."""
        return self._data.get(symbol.upper())

    def evaluate_signal(
        self,
        symbol: str,
        side: str  # "LONG" or "SHORT"
    ) -> Tuple[bool, str]:
        """
        Evaluate if a signal should proceed based on market conditions.

        Checks:
        1. Funding Rate: Block trades against crowded direction
        2. Symbol Availability: Check if data exists

        Args:
            symbol: Trading pair (e.g., "ZECUSDT")
            side: Trade direction ("LONG" or "SHORT")

        Returns:
            (should_proceed, reason_if_blocked)
        """
        symbol = symbol.upper()
        side = side.upper()

        intel = self._data.get(symbol)

        if not intel:
            # No intelligence data, allow trade but log warning
            self.logger.debug(f"⚠️ No intelligence for {symbol}, allowing trade")
            return True, ""

        funding = intel.funding_rate

        # Check adverse funding for SHORT
        if side == "SHORT" and funding < self.FUNDING_THRESHOLD_NEGATIVE:
            reason = (
                f"Funding {funding:.3f}% adverse for SHORT. "
                f"Crowded shorts - squeeze risk!"
            )
            return False, reason

        # Check adverse funding for LONG
        if side == "LONG" and funding > self.FUNDING_THRESHOLD_POSITIVE:
            reason = (
                f"Funding +{funding:.3f}% adverse for LONG. "
                f"Crowded longs - squeeze risk!"
            )
            return False, reason

        # Extreme warnings (still allow but log)
        if funding > self.FUNDING_EXTREME_POSITIVE:
            self.logger.warning(f"🔴 EXTREME funding +{funding:.3f}% on {symbol}")
        elif funding < self.FUNDING_EXTREME_NEGATIVE:
            self.logger.warning(f"🔴 EXTREME funding {funding:.3f}% on {symbol}")

        return True, ""

    def get_capped_leverage(self, symbol: str, desired_leverage: int) -> int:
        """
        Get leverage capped to exchange maximum.

        Args:
            symbol: Trading pair
            desired_leverage: Leverage bot wants to use

        Returns:
            Capped leverage (min of desired and max allowed)
        """
        symbol = symbol.upper()
        intel = self._data.get(symbol)

        if not intel:
            # Default max leverage if no data
            return min(desired_leverage, 10)

        max_lev = intel.max_leverage
        capped = min(desired_leverage, max_lev)

        if capped < desired_leverage:
            self.logger.info(
                f"⚙️ {symbol}: Leverage capped {desired_leverage}x → {capped}x (max: {max_lev}x)"
            )

        return capped

    def get_funding_direction_hint(self, symbol: str) -> str:
        """
        Get trading direction hint based on funding rate.

        Returns:
            "LONG_PREFERRED", "SHORT_PREFERRED", or "NEUTRAL"
        """
        symbol = symbol.upper()
        intel = self._data.get(symbol)

        if not intel:
            return "NEUTRAL"

        funding = intel.funding_rate

        if funding < self.FUNDING_THRESHOLD_NEGATIVE:
            # Shorts are paying longs - go long to collect funding
            return "LONG_PREFERRED"
        elif funding > self.FUNDING_THRESHOLD_POSITIVE:
            # Longs are paying shorts - go short to collect funding
            return "SHORT_PREFERRED"
        else:
            return "NEUTRAL"

    def get_stats(self) -> Dict:
        """Get service statistics."""
        if not self._loaded:
            return {"loaded": False}

        return {
            "loaded": True,
            "symbols_count": len(self._data),
            "last_refresh": self._last_refresh.isoformat() if self._last_refresh else None,
            "file_path": self._file_path,
            "funding_alerts": sum(
                1 for intel in self._data.values()
                if abs(intel.funding_rate) > self.FUNDING_THRESHOLD_POSITIVE
            )
        }

    @property
    def is_loaded(self) -> bool:
        return self._loaded

    def get_all_symbols(self) -> list:
        """Get list of all symbols with intelligence data."""
        return list(self._data.keys())

    def get_funding_summary(self) -> Dict[str, Dict]:
        """Get funding rate summary for all symbols."""
        return {
            sym: {
                "funding_rate": intel.funding_rate,
                "direction_hint": self.get_funding_direction_hint(sym),
                "max_leverage": intel.max_leverage
            }
            for sym, intel in self._data.items()
        }

    def fetch_and_update(self, client = None) -> bool:
        """
        SOTA: Fetch intelligence from API (ALL USDT pairs) and update cache.
        Automated data collection integrated into the application.
        """
        try:
            # Lazy import to avoid circular dependency
            from ..api.binance_futures_client import BinanceFuturesClient

            # Use provided client or create new one (public data doesn't need keys)
            local_client = client
            if not local_client:
                # Default to PRODUCTION for market data (Paper trading simulates production)
                local_client = BinanceFuturesClient(use_testnet=False)

            self.logger.info("🧠 SOTA: Fetching Market Intelligence (ALL USDT Pairs)...")

            # 1. Exchange Info (Rules)
            info = local_client.get_exchange_info()
            if not info or 'symbols' not in info:
                self.logger.error("Failed to fetch exchange info")
                return False

            # 2. Premium Index (Funding Rates)
            # Use public request via client
            funding_data = local_client._send_public_request("/fapi/v1/premiumIndex")
            funding_map = {item['symbol']: item for item in funding_data}

            # 3. Process Data
            results = {}
            for s in info['symbols']:
                sym = s['symbol']
                if not sym.endswith('USDT'): continue # Only USDT pairs

                # Filters
                filters = {f['filterType']: f for f in s['filters']}
                min_qty = float(filters.get('LOT_SIZE', {}).get('minQty', 0))
                max_qty = float(filters.get('LOT_SIZE', {}).get('maxQty', 1000000))
                step_size = float(filters.get('LOT_SIZE', {}).get('stepSize', 0))
                tick_size = float(filters.get('PRICE_FILTER', {}).get('tickSize', 0))
                min_notional = float(filters.get('MIN_NOTIONAL', {}).get('notional', 5.0))
                precision_qty = int(s.get('quantityPrecision', 3))
                precision_price = int(s.get('pricePrecision', 2))

                # Market Data
                f_data = funding_map.get(sym, {})
                # fundingRate is string in API
                funding_rate = float(f_data.get('lastFundingRate', 0)) * 100
                next_funding_time = "N/A"
                if 'nextFundingTime' in f_data:
                    # Convert ms timestamp
                    next_funding_time = datetime.fromtimestamp(f_data['nextFundingTime']/1000).strftime('%H:%M:%S')
                mark_price = float(f_data.get('markPrice', 0))

                # Leverage (Public API doesn't give leverage brackets without keys)
                # We use defaults or cached values if available, or conservative defaults
                # SOTA: Keep existing logic or default to 20x if unknown to be safe
                max_lev = 20
                max_pos = 1000000

                # Structure
                results[sym] = {
                    "rules": {
                        "min_qty": min_qty,
                        "max_qty": max_qty,
                        "step_size": step_size,
                        "tick_size": tick_size,
                        "min_notional": min_notional,
                        "qty_precision": precision_qty,
                        "price_precision": precision_price
                    },
                    "risk": {
                        "max_leverage": max_lev,
                        "max_position_at_max_leverage": max_pos
                    },
                    "market": {
                        "funding_rate": funding_rate,
                        "next_funding_time": next_funding_time,
                        "mark_price": mark_price
                    }
                }

            # 4. Save to JSON Cache
            if not self._file_path:
                # Determine path if not set
                base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
                self._file_path = os.path.join(base_dir, "data", "market_intelligence.json")

            os.makedirs(os.path.dirname(self._file_path), exist_ok=True)
            with open(self._file_path, 'w') as f:
                json.dump(results, f, indent=2)

            self.logger.info(f"✅ Intelligence updated for {len(results)} symbols. Cache saved.")

            # 5. Reload Memory
            return self.load_from_file(self._file_path)

        except Exception as e:
            self.logger.error(f"❌ Failed to update intelligence: {e}")
            import traceback
            self.logger.error(traceback.format_exc())
            return False
