"""Signal strategy identifiers shared by CLI, DI, and tests."""

from ...domain.entities.strategy_contract import (
    DONCHIAN_BREAKOUT_RUNNER,
    MEAN_REVERSION_SCALPER,
    MOMENTUM_PULLBACK_RUNNER,
    TREND_CONTINUATION_RUNNER,
)

DEFAULT_STRATEGY_ID = MEAN_REVERSION_SCALPER.strategy_id
TREND_RUNNER_STRATEGY_ID = TREND_CONTINUATION_RUNNER.strategy_id
DONCHIAN_BREAKOUT_STRATEGY_ID = DONCHIAN_BREAKOUT_RUNNER.strategy_id
MOMENTUM_PULLBACK_STRATEGY_ID = MOMENTUM_PULLBACK_RUNNER.strategy_id

SUPPORTED_STRATEGY_IDS = (
    DEFAULT_STRATEGY_ID,
    TREND_RUNNER_STRATEGY_ID,
    DONCHIAN_BREAKOUT_STRATEGY_ID,
    MOMENTUM_PULLBACK_STRATEGY_ID,
)
