"""Signal strategy identifiers shared by CLI, DI, and tests."""

from ...domain.entities.strategy_contract import MEAN_REVERSION_SCALPER, TREND_CONTINUATION_RUNNER

DEFAULT_STRATEGY_ID = MEAN_REVERSION_SCALPER.strategy_id
TREND_RUNNER_STRATEGY_ID = TREND_CONTINUATION_RUNNER.strategy_id

SUPPORTED_STRATEGY_IDS = (
    DEFAULT_STRATEGY_ID,
    TREND_RUNNER_STRATEGY_ID,
)
